In [1]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import time
import math

from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OneHotEncoder

data_path = '../raw_data/100k_data.csv'
df_all = pd.read_csv(data_path)
df_all = df_all.dropna()
df_sample = df_all.dropna().sample(10000,random_state=0)

In [3]:
def binary_cat_upvotes(original_df, threshold=30):
    """
    Takes column from df called 'upvotes' and returns df with new column
    'cat_upvotes' which is 1 if upvotes is above threshold, and 0 otherwise.
    """
    df = original_df.copy()
    if 'upvotes' not in original_df.columns:
        raise ValueError("df has no column named 'upvotes'")
    def trans(number):
        if number >= threshold:
            return 1
        else:
            return 0
    df['cat_upvotes'] = df['upvotes'].apply(trans)
    return df

In [6]:
df_new = df_all[['title','upvotes']]
df_new

                                                   title  upvotes
0                                   i'm going to walmart        1
1      After suffering from 2 cherry eye look at how ...       16
2                                            Pets please       31
3                            Enjoying some Ice Cream :-)       13
4            What do you guys think of my grandma’s dog?        1
...                                                  ...      ...
99260                                It's so green here!     1019
99262          My vicious beast trying to catch his toy.       12
99263      Kiley, 14 years old and more regal than ever.      139
99264  My boys Kylo (left) and Peanut (right) love St...       30
99265                                            HEAVEN!       13

[72763 rows x 2 columns]

In [7]:
df_new = binary_cat_upvotes(df_new)
df_new

                                                   title  upvotes  cat_upvotes
0                                   i'm going to walmart        1            0
1      After suffering from 2 cherry eye look at how ...       16            0
2                                            Pets please       31            1
3                            Enjoying some Ice Cream :-)       13            0
4            What do you guys think of my grandma’s dog?        1            0
...                                                  ...      ...          ...
99260                                It's so green here!     1019            1
99262          My vicious beast trying to catch his toy.       12            0
99263      Kiley, 14 years old and more regal than ever.      139            1
99264  My boys Kylo (left) and Peanut (right) love St...       30            1
99265                                            HEAVEN!       13            0

[72763 rows x 3 columns]

In [8]:
df_new = df_new.drop(columns='upvotes')
df_new

                                                   title  cat_upvotes
0                                   i'm going to walmart            0
1      After suffering from 2 cherry eye look at how ...            0
2                                            Pets please            1
3                            Enjoying some Ice Cream :-)            0
4            What do you guys think of my grandma’s dog?            0
...                                                  ...          ...
99260                                It's so green here!            1
99262          My vicious beast trying to catch his toy.            0
99263      Kiley, 14 years old and more regal than ever.            1
99264  My boys Kylo (left) and Peanut (right) love St...            1
99265                                            HEAVEN!            0

[72763 rows x 2 columns]

In [9]:
def title_len(string):
    return len(string)

df_new['title_len'] = df_new['title'].apply(title_len)
df_new

,title,cat_upvotes,title_len
0,i'm going to walmart,0,20
1,After suffering from 2 cherry eye look at how ...,0,74
2,Pets please,1,11
3,Enjoying some Ice Cream :-),0,27
4,What do you guys think of my grandma’s dog?,0,43
...,...,...,...
99260,It's so green here!,1,19
99262,My vicious beast trying to catch his toy.,0,41
99263,"Kiley, 14 years old and more regal than ever.",1,45
99264,My boys Kylo (left) and Peanut (right) love St...,1,56
99265,HEAVEN!,0,7

In [12]:
pd.set_option('display.max_rows', None)
df_new.groupby('title_len').mean('cat_upvotes')

           cat_upvotes
title_len
1             0.014706
2             0.022727
3             0.093264
4             0.219451
5             0.231707
6             0.224335
7             0.216599
8             0.224204
9             0.216783
10            0.266289
11            0.253401
12            0.233308
13            0.257554
14            0.266525
15            0.263595
16            0.270864
17            0.263870
18            0.301950
19            0.274270
20            0.272404
21            0.289925
22            0.282744
23            0.277971
24            0.267756
25            0.281411
26            0.269695
27            0.275562
28            0.287923
29            0.317014
30            0.280979
31            0.299282
32            0.301146
33            0.303215
34            0.306480
35            0.321492
36            0.310098
37            0.289855
38            0.346304
39            0.303761
40            0.307453
41            0.328962
42            0.307779
43            0.317647
44            0.301205
45            0.332143
46            0.362003
47            0.346467
48            0.301059
49            0.316017
50            0.305296
51            0.313146
52            0.297342
53            0.301989
54            0.316667
55            0.333333
56            0.324910
57            0.307544
58            0.330579
59            0.331276
60            0.297240
61            0.335616
62            0.323040
63            0.335013
64            0.347619
65            0.335106
66            0.304762
67            0.340314
68            0.329670
69            0.331378
70            0.359756
71            0.350575
72            0.362776
73            0.372822
74            0.338078
75            0.317308
76            0.324528
77            0.327068
78            0.354331
79            0.423729
80            0.343891
81            0.342222
82            0.341564
83            0.377358
84            0.388128
85            0.353591
86            0.391534
87            0.331754
88            0.365979
89            0.337931
90            0.354286
91            0.354037
92            0.343195
93            0.395833
94            0.381944
95            0.430303
96            0.450867
97            0.316129
98            0.455882
99            0.345912
100           0.350746
101           0.414141
102           0.392000
103           0.369748
104           0.419355
105           0.403226
106           0.403361
107           0.439024
108           0.400000
109           0.309091
110           0.367347
111           0.478261
112           0.432990
113           0.411111
114           0.318681
115           0.413793
116           0.350000
117           0.404762
118           0.267606
119           0.337838
120           0.454545
121           0.341463
122           0.457831
123           0.420290
124           0.367647
125           0.435294
126           0.428571
127           0.437500
128           0.338983
129           0.400000
130           0.474576
131           0.400000
132           0.310345
133           0.396552
134           0.274510
135           0.408163
136           0.425532
137           0.314815
138           0.250000
139           0.340426
140           0.431818
141           0.446809
142           0.470588
143           0.465116
144           0.395349
145           0.235294
146           0.560976
147           0.428571
148           0.432432
149           0.456522
150           0.475000
151           0.485714
152           0.312500
153           0.360000
154           0.444444
155           0.500000
156           0.340909
157           0.454545
158           0.500000
159           0.350000
160           0.379310
161           0.375000
162           0.571429
163           0.450000
164           0.444444
165           0.285714
166           0.433333
167           0.384615
168           0.500000
169           0.318182
170           0.458333
171           0.318182
172           0.428571
173           0.407407
174           0.357143
175           0.550000
176           0.304348
177           0.388889
178           0.173913
179           0.538462
180           0.294118
181           0.461538
182           0.450000
183           0.363636
184           0.421053
185           0.190476
186           0.555556
187           0.588235
188           0.500000
189           0.687500
190           0.500000
191           0.294118
192           0.333333
193           0.714286
194           0.142857
195           0.461538
196           0.583333
197           0.428571
198           0.416667
199           0.384615
200           0.409091
201           0.272727
202           0.450000
203           0.529412
204           0.333333
205           0.363636
206           0.562500
207           0.500000
208           0.444444
209           0.454545
210           0.545455
211           0.400000
212           0.454545
213           0.312500
214           0.500000
215           0.444444
216           0.333333
217           0.166667
218           0.750000
219           0.285714
220           0.300000
221           0.333333
222           0.571429
223           0.357143
224           0.500000
225           0.428571
226           0.555556
227           0.333333
228           0.500000
229           0.400000
230           0.222222
231           0.300000
232           0.111111
233           0.545455
234           0.500000
235           0.250000
236           0.500000
237           0.428571
238           0.416667
239           0.666667
240           0.428571
241           0.222222
242           0.857143
243           0.500000
244           0.400000
245           0.500000
246           0.333333
247           0.285714
248           0.400000
249           0.444444
250           0.285714
251           0.250000
252           0.125000
253           0.500000
254           0.714286
255           0.400000
256           0.500000
257           0.500000
258           0.400000
259           0.400000
260           0.384615
261           0.000000
262           0.333333
263           1.000000
264           0.333333
265           0.636364
266           0.600000
267           0.800000
268           0.500000
269           0.000000
270           0.571429
271           0.222222
272           0.600000
273           0.666667
274           0.750000
275           0.000000
276           0.000000
277           0.166667
278           0.416667
280           0.333333
281           0.500000
282           0.500000
283           0.200000
284           0.750000
285           0.500000
286           0.400000
287           0.416667
288           0.666667
289           0.166667
290           0.125000
291           0.200000
292           0.461538
293           0.500000
294           0.375000
295           0.285714
296           0.312500
297           0.333333
298           0.176471
299           0.500000
300           0.387097